services:
  api:
    container_name: brain_ag_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: .
    volumes:
      - ./brain_ag:/src
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    container_name: brain_ag_db
    image: postgres:16
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brain_ag_dev_admin
      - POSTGRES_PASSWORD=brain_ag_dev_password
      - POSTGRES_DB=brain_ag_dev
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default


volumes:
  postgres_data:
    name: postgres_data