# Generated by Django 5.1 on 2024-08-26 23:58

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuralProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4)),
                ('doc_number', models.CharField(max_length=18, unique=True, validators=[api.validators.validate_doc_number], verbose_name='CPF or CNPJ')),
                ('producer_name', models.CharField(max_length=255, verbose_name='Producer Name')),
                ('farm_name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Area (ha)')),
                ('arable_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Arable Area (ha)')),
                ('vegetation_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vegetation Area (ha)')),
                ('planted_crops', models.ManyToManyField(to='api.crop', verbose_name='Planted Crops')),
            ],
        ),
    ]
